# Generated by Django 4.1.6 on 2023-03-09 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("propertyManager", "0003_remove_propertydetail_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertydetail",
            name="owner",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
